//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSecenek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnketSecenek()
        {
            this.AnketCevap = new HashSet<AnketCevap>();
        }
    
        public int anketSecenekID { get; set; }
        public int anketSoruID { get; set; }
        public string anketSecenekIcerik { get; set; }
        public short anketSecenekPuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevap> AnketCevap { get; set; }
        public virtual AnketSoru AnketSoru { get; set; }
    }
}
