//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsilListe
    {
        public int asilListeID { get; set; }
        public int birimKontejyanID { get; set; }
        public int bolumKontejyanID { get; set; }
        public int ogrenciID { get; set; }
        public int personelID { get; set; }
        public System.DateTime asilListeEklemeTarih { get; set; }
        public Nullable<System.DateTime> asilListeGuncellemeTarih { get; set; }
    
        public virtual BirimKontejyan BirimKontejyan { get; set; }
        public virtual BolumKontejyan BolumKontejyan { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
