//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirimFiyat
    {
        public int birimFiyatID { get; set; }
        public int calismaTipID { get; set; }
        public decimal birimFiyati { get; set; }
    
        public virtual CalismaTip CalismaTip { get; set; }
    }
}
