//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolumKontejyan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BolumKontejyan()
        {
            this.AsilListe = new HashSet<AsilListe>();
            this.Bolum = new HashSet<Bolum>();
        }
    
        public int bolumKontejyanID { get; set; }
        public short bolumKontejyanAkademi { get; set; }
        public short bolumKontejyanIdari { get; set; }
        public short bolumKontejyanEkAkademi { get; set; }
        public short bolumKontejyanEkIdari { get; set; }
        public string bolumKontejyanAkademiNot { get; set; }
        public string bolumKontejyanIdarıNot { get; set; }
        public System.DateTime bolumKontejyanEklemeTarih { get; set; }
        public Nullable<System.DateTime> bolumKontejyanGuncellemeTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsilListe> AsilListe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bolum> Bolum { get; set; }
    }
}
