//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bolum()
        {
            this.CalismaYeri = new HashSet<CalismaYeri>();
            this.CikanKisi = new HashSet<CikanKisi>();
            this.EklenenKisi = new HashSet<EklenenKisi>();
            this.Mulakat = new HashSet<Mulakat>();
            this.Personel = new HashSet<Personel>();
        }
    
        public int bolumID { get; set; }
        public string bolumAd { get; set; }
        public int birimID { get; set; }
        public int bolumKontejyanID { get; set; }
        public int bolumAkademikCalisan { get; set; }
        public int bolumIdariCalisan { get; set; }
        public System.DateTime bolumEklemeTarih { get; set; }
        public Nullable<System.DateTime> bolumGuncellemeTarih { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual BolumKontejyan BolumKontejyan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalismaYeri> CalismaYeri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CikanKisi> CikanKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EklenenKisi> EklenenKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mulakat> Mulakat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personel> Personel { get; set; }
    }
}
