//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalismaYeri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalismaYeri()
        {
            this.CalisanYoklama = new HashSet<CalisanYoklama>();
            this.CikanKisi = new HashSet<CikanKisi>();
            this.OgrenciCalisma = new HashSet<OgrenciCalisma>();
        }
    
        public int calismaYeriID { get; set; }
        public int birimID { get; set; }
        public int bolumID { get; set; }
        public int calismaTipID { get; set; }
        public int ogrenciID { get; set; }
        public System.DateTime calismaYeriSgkGirisTarih { get; set; }
        public Nullable<System.DateTime> calismaYeriSgkCikisTarih { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalisanYoklama> CalisanYoklama { get; set; }
        public virtual CalismaTip CalismaTip { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CikanKisi> CikanKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciCalisma> OgrenciCalisma { get; set; }
    }
}
