//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalisanYoklama
    {
        public int calisanYoklamaID { get; set; }
        public int calismaYeriID { get; set; }
        public System.DateTime calisanYoklamaGun { get; set; }
        public decimal calisanYoklamaSaat { get; set; }
        public System.DateTime calisanEklemeTarih { get; set; }
        public Nullable<System.DateTime> calisanGuncellemeTarih { get; set; }
    
        public virtual CalismaYeri CalismaYeri { get; set; }
    }
}
