//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EklenenKisi
    {
        public int eklenenKisiID { get; set; }
        public int birimID { get; set; }
        public int bolumID { get; set; }
        public string eklenenKisiTC { get; set; }
        public string eklenenKisiOgrenciNo { get; set; }
        public string eklenenKisiAd { get; set; }
        public string eklenenKisiSoyad { get; set; }
        public int personelID { get; set; }
        public string eklenenKisiAciklama { get; set; }
        public System.DateTime eklenenKisiEklemeTarih { get; set; }
        public Nullable<System.DateTime> eklenenKisiGuncellemeTarih { get; set; }
        public Nullable<System.DateTime> eklenenKisiGorulmeTarih { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual Bolum Bolum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
