//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngelDurum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngelDurum()
        {
            this.Ogrenci = new HashSet<Ogrenci>();
            this.OgrenciCalisma = new HashSet<OgrenciCalisma>();
        }
    
        public int engelDurumID { get; set; }
        public string engelDurumIcerik { get; set; }
        public decimal engelDurumOran { get; set; }
        public decimal engelDurumIndirilen { get; set; }
        public decimal engelDurumSgkPrim { get; set; }
        public decimal engelDurumIssizlikFon { get; set; }
        public System.DateTime engelDurumEklemeTarih { get; set; }
        public Nullable<System.DateTime> engelDurumGuncellemeTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrenci> Ogrenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciCalisma> OgrenciCalisma { get; set; }
    }
}
