//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsTakip
    {
        public int isTakipID { get; set; }
        public string isTakipBaslik { get; set; }
        public string isTakipIcerik { get; set; }
        public System.DateTime isTakipEklemeTarih { get; set; }
        public Nullable<System.DateTime> isTakipGuncellemeTarih { get; set; }
        public Nullable<System.DateTime> isTakipBitirmeTarih { get; set; }
        public string isTakipKontrol { get; set; }
        public int ogrenciID { get; set; }
        public int personelID { get; set; }
        public string isTakipSonuc { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
