//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muhasebe
    {
        public int muhasebeID { get; set; }
        public decimal muhasebeAsgariBrut { get; set; }
        public decimal muhasebeAsgariNet { get; set; }
        public decimal muhasebeAsgariGun { get; set; }
        public decimal muhasebeGelirVergiOran { get; set; }
        public decimal muhasebeDamgaVergiOran { get; set; }
        public decimal muhasebeGSS43Oran { get; set; }
        public decimal muhasebeAzamiGunCalisma { get; set; }
        public System.DateTime muhasebeEklemeTarih { get; set; }
        public Nullable<System.DateTime> muhasebeGuncellemeTarih { get; set; }
    }
}
