//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mulakat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mulakat()
        {
            this.MulakatSoru = new HashSet<MulakatSoru>();
        }
    
        public int mulakatID { get; set; }
        public int ilanID { get; set; }
        public int birimID { get; set; }
        public int bolumID { get; set; }
        public System.DateTime mulakatEklemeTarih { get; set; }
        public Nullable<System.DateTime> mulakatGuncellemeTarih { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual Bolum Bolum { get; set; }
        public virtual Ilan Ilan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatSoru> MulakatSoru { get; set; }
    }
}
