//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int kullaniciID { get; set; }
        public string ogrenciTC { get; set; }
        public string ogrenciNumara { get; set; }
        public string ogrenciAd { get; set; }
        public string ogrenciSoyad { get; set; }
        public System.DateTime ogrenciDogumTarih { get; set; }
        public string ogrenciMail { get; set; }
        public string ogrenciTelNo { get; set; }
        public string ogrenciIBAN { get; set; }
        public decimal ogrenciNotOrt { get; set; }
        public int okulID { get; set; }
        public int okulBolumID { get; set; }
        public int sinifID { get; set; }
        public int ogrenimTurID { get; set; }
        public int ogrenimTipID { get; set; }
        public int calismaTipID { get; set; }
        public bool ogrenciAktiflik { get; set; }
        public int aileSgkID { get; set; }
        public int ogrenciAnketPuan { get; set; }
        public int engelDurumID { get; set; }
        public System.DateTime ogrenciEklemeTarih { get; set; }
        public Nullable<System.DateTime> ogrenciGuncellemeTarih { get; set; }
        public int ogrenciID { get; set; }
    
        public virtual AileSgk AileSgk { get; set; }
        public virtual EngelDurum EngelDurum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual OgrenimTip OgrenimTip { get; set; }
        public virtual OgrenimTur OgrenimTur { get; set; }
        public virtual Okul Okul { get; set; }
        public virtual OkulBolum OkulBolum { get; set; }
        public virtual Sinif Sinif { get; set; }
    }
}
