//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciBasvuru
    {
        public int ogrenciBasvuruID { get; set; }
        public int ogrenciID { get; set; }
        public byte ogrenciBasvuruSayisi { get; set; }
        public int ilanID { get; set; }
        public short ogrenciBasvuruMulakatPuan { get; set; }
        public System.DateTime ogrenciBasvuruEklemeTarih { get; set; }
        public Nullable<System.DateTime> ogrenciBasvuruGuncellemeTarih { get; set; }
    
        public virtual Ilan Ilan { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
