//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciCalisma
    {
        public int ogrenciCalismaID { get; set; }
        public int ogrenciID { get; set; }
        public int calismaYeriID { get; set; }
        public byte ogrenciCalismaSaat { get; set; }
        public byte ogrenciCalismaGun { get; set; }
        public decimal birimFiyati { get; set; }
        public int ogrenimTipID { get; set; }
        public decimal ogrenciCalismaAsgariGunBrut { get; set; }
        public decimal ogrenciCalismaBrutUcret1 { get; set; }
        public decimal ogrenciCalismaSgkPrimHesabi { get; set; }
        public int yasalKesintiID { get; set; }
        public decimal ogrenciCalismaDamgaVergisi { get; set; }
        public decimal ogrenciCalismaGelirVergisi { get; set; }
        public string aileSgkKod { get; set; }
        public decimal ogrenciCalismaGSS43Prim { get; set; }
        public System.DateTime ogrenciCalismaEklemeTarih { get; set; }
        public System.DateTime ogrenciCalismaAitOlduguAy { get; set; }
        public decimal ogrenciCalismaNetUcret { get; set; }
        public int engelDurumID { get; set; }
        public decimal ogrenciCalismaEngelBrut1 { get; set; }
    
        public virtual CalismaYeri CalismaYeri { get; set; }
        public virtual EngelDurum EngelDurum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual OgrenimTip OgrenimTip { get; set; }
        public virtual YasalKesinti YasalKesinti { get; set; }
    }
}
