//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.PersonelYetki = new HashSet<PersonelYetki>();
        }
    
        public int kullaniciID { get; set; }
        public string personelTC { get; set; }
        public string personelAd { get; set; }
        public string personelSoyad { get; set; }
        public string personelDahiliNo { get; set; }
        public string personelUnvan { get; set; }
        public int birimID { get; set; }
        public int bolumID { get; set; }
        public System.DateTime personelEklemeTarih { get; set; }
        public Nullable<System.DateTime> personelGuncellemeTarih { get; set; }
        public int personelID { get; set; }
    
        public virtual Birim Birim { get; set; }
        public virtual Bolum Bolum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelYetki> PersonelYetki { get; set; }
    }
}
