//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YasalKesinti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YasalKesinti()
        {
            this.OgrenciCalisma = new HashSet<OgrenciCalisma>();
        }
    
        public int yasalKesintiID { get; set; }
        public int ogrenciID { get; set; }
        public string yasalKesintiIcerik { get; set; }
        public decimal yasalKesintiOran { get; set; }
        public decimal yasalKesintiBorc { get; set; }
        public decimal yasalKesintiKalanBorc { get; set; }
        public System.DateTime yasalKesintiEklemeTarih { get; set; }
        public Nullable<System.DateTime> yasalKesintiGuncellemeTarih { get; set; }
        public Nullable<System.DateTime> yasalKesintiBitisTarih { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciCalisma> OgrenciCalisma { get; set; }
    }
}
