//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SksCalisma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YetkiTip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YetkiTip()
        {
            this.PersonelYetki = new HashSet<PersonelYetki>();
        }
    
        public int yetkiTipID { get; set; }
        public string yetkiTipAd { get; set; }
        public System.DateTime yetkiTipEklemeTarih { get; set; }
        public Nullable<System.DateTime> yetkiTipGuncellemeTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelYetki> PersonelYetki { get; set; }
    }
}
